# SPDX-FileCopyrightText: 2020 Memories Project
#
# SPDX-License-Identifier: Apache-2.0

name: Sonar Cloud

on:
  push:
    branches:
      - development

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-18.04']
        java: [ '11' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: x64

      - name: actions/test
        run: |
          export JAVA_HOME=$JAVA_HOME
          export JAVA_HOME_JDK2=$JAVA_HOME
          sudo apt-get install musl-dev
          sudo ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
          ./mvnw -t .mvn/toolchains.xml clean package jacoco:report-aggregate sonar:sonar -Pdevelopment -Pcoverage -Pformat -Psonar -Dsonar.login="${{ secrets.SONAR_TOKEN }}" -Dsonar.projectKey=ardikars_memories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}